language: cpp

os:
  - osx

osx_image: xcode8.2
xcode_project: pixelpunch.xcodeproj
osx_sdk: macosx10.12

compiler:
  - clang
  - gcc

before_install:
  - brew update
  # - brew install xctool
  - brew install Caskroom/cask/cinder

script: xcodebuild clean build -project xcode/pixelpunch.xcodeproj OTHER_LDFLAGS="/Applications/cinder_0.9.0_mac/lib" HEADER_SEARCH_PATHS="/Applications/cinder_0.9.0_mac/include"  -configuration “Build” -scheme pixelpunch
