version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: x64
install:
- ps: >-
    Start-FileDownload 'https://libcinder.org/static/releases/cinder_0.9.0_vc2013.zip'

    7z e cinder_0.9.0_vc2013.zip -oc:\project\cinder_0.9.0_vc2013
before_build:
- cmd: >-
    set "INCLUDE="C:\project\cinder_0.9.0_vc2013\include";%INCLUDE%"
    set "LIB="C:\project\cinder_0.9.0_vc2013\lib\msw";%LIB%"
    set UseEnv=true
build:
  project: vc11/PixelPunch.vcxproj
  verbosity: minimal