version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: x64
environment:
  INCLUDE: C:\projects\cinder_0.9.0_vc2013\include
  LIB:     C:\projects\cinder_0.9.0_vc2013\lib
install:
- ps: >-
    Start-FileDownload 'https://libcinder.org/static/releases/cinder_0.9.0_vc2013.zip'

    7z x cinder_0.9.0_vc2013.zip -oc:\projects\
before_build:
- cmd: >-
    dir
    cd \projects\cinder_0.9_0_vc2013
    dir
    cd ..\
    echo %LIB%
    echo %INCLUDE%
build:
  project: vc11/PixelPunch.vcxproj
  verbosity: minimal