version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
configuration: Release
platform: x64
environment:
  INCLUDE: C:\projects\cinder_0.9.0_vc2013\include
  LIB:     C:\projects\cinder_0.9.0_vc2013\lib

cache:
- C:\projects\cinder_0.9.0_vc2013 -> appveyor.yml
install:
- ps: >-
    Start-FileDownload 'https://libcinder.org/static/releases/cinder_0.9.0_vc2013.zip'

    7z x cinder_0.9.0_vc2013.zip -oc:\projects\
before_build:
- cmd: >-
    set UseEnv=true

build:
  project: vc11/PixelPunch.vcxproj
  verbosity: minimal