version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: x64
install:
- ps: Start-FileDownload 'https://libcinder.org/static/releases/cinder_0.9.0_vc2013.zip'
before_build:
- ps: 
build:
  project: vc11/PixelPunch.vcxproj
  verbosity: minimal