version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
image: Visual Studio 2015

configuration: Release
platform: x64
install:
- ps: Start-FileDownload 'https://libcinder.org/static/releases/cinder_0.9.0_vc2013.zip'

cache: C:\projects\cinder_0.9.0_vc2013

before_build:
- cmd: set UseEnv=true
build:
  project: vc11/PixelPunch.vcxproj
  verbosity: minimal

build_script:
  - cmd: set INCLUDE=C:\projects\cinder_0.9.0_vc2013\include;%INCLUDE%
  - cmd: set LIB=C:\projects\cinder_0.9.0_vc2013\lib;%LIB%
  - cmd: call "%VS140COMNTOOLS%vsvars32.bat"
  - cmd: call MSBuild.exe c:\projects\pixelpunch\vc11\pixelpunch.vcxproj /p:Configuration=Release;Verbosity=minimal 