version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: x64
install:
- ps: Start-FileDownload 'https://libcinder.org/static/releases/cinder_0.9.0_vc2013.zip'
before_build:
- cmd: >-
    set "INCLUDE="C:\project\cinder_0.9.0_vc2013\include";%INCLUDE%"
    set "LIB="C:\project\cinder_0.9.0_vc2013\lib\cinder_d.lib; C:\project\cinder_0.9.0_vc2013\lib\cinder.lib";%LIB%"
    set UseEnv=true
build:
  project: vc11/PixelPunch.vcxproj
  verbosity: minimal